### ISSUE TITLE
UI Theme of the screenshot

### ISSUE THREAD

**Issue by dohvahkhin** [Tehnix/spacemacsdark-syntax-atom#3]
sorry i'm pretty new to github i don't know if it is the right way to contact you to ask this question ^^
anyway i like the UI theme in the screenshot of the spacemacs-dark syntax theme for atom and i wanted to know if you could tell me the name ? thanks

**Comment by Tehnix** [comment]
No worries, ask all you want! :)

The theme is taken from [Spacemacs](http://spacemacs.org) and called _Spacemacs Dark_, originally from [here](https://github.com/nashamri/spacemacs-theme). It exists for multiple other editors also if you are interested. Obviously emacs (since spacemacs is emacs), and also for Vim/Neovim [here](https://github.com/liuchengxu/space-vim-dark) and VSCode [here](https://github.com/cometeer/spacemacs-vscode).

Was there anything in particular you were interested in? Btw, I did not create it, just use it in all my editor setups for a more seamless switching.

**Comment by Tehnix** [comment]
Ah sheesh, I think I misunderstood. The _UI_ theme is just _One Dark_ with some custom CSS in my Atom stylesheet. I'd advise checking the default, and then maybe cherry picking some of my changes. Most are actually for the cursor line and vim-mode.

```css
// Style the cursor
atom-text-editor.vim-mode-plus.normal-mode.is-focused, atom-text-editor.vim-mode-plus.command-mode.is-focused, atom-text-editor.vim-mode-plus.operator-pending-mode.is-focused, atom-text-editor.vim-mode-plus.visual-mode.is-focused,
atom-text-editor.vim-mode-plus.insert-mode.is-focused {
    & {
        // Make the cursor underline
        // .cursor, .cursor.blink-off {
        //     background-color: transparent;
        //     border: none;
        //     opacity: 1;
        //     color: transparent;
        //     border-bottom-color: #fff;
        //     border-bottom-style: solid;
        // }
        // Make the cursor a vertical bar
        .cursor, .cursor.blink-off {
            background-color: #fff;
            // border: none;
            // opacity: 1;
            // color: transparent;
            // border-left-color: #fff;
            // border-left-width: 1px;
            // border-left-style: solid;
        }
    }
}
// When in insert mode, make the underline a bit thinner and yellow
atom-text-editor.vim-mode-plus.insert-mode.is-focused {
    & {
        // Orange cursor in insert mode (underline)
        // .cursor, .cursor.blink-off {
        //     border-bottom-color: #FFB800;
        //     border-bottom-width: 1px;
        // }
        // Orange cursor in insert mode (vertical bar)
        .cursor, .cursor.blink-off {
            background-color: transparent;
            opacity: 1;
            border-left-color: #FFB800;
            border-left-width: 1px;
        }
    }
}
// Change the VIM mode text to yellow when in insert mode
#status-bar-vim-mode-plus.status-bar-vim-mode-plus-insert {
    color: #FFB800;
}

.cursor-line-background(@mode, @color) {
  atom-text-editor.vim-mode-plus.@{mode}.is-focused {
    & .lines .line.cursor-line {
      background-color: @color
    }
  }
}
.cursor-line-background(normal-mode, fadeout(gray, 85%));
.cursor-line-background(insert-mode, fadeout(orange, 90%));
.cursor-line-background(operator-pending-mode, fadeout(yellow, 85%));

// Style Atom-material UI.
.amu-compact-tab-bar {
  .tab-bar[location="bottom"] {
      @tabHeight: 1rem;
      height: @tabHeight;
      max-height: @tabHeight;
      .tab {
        height: @tabHeight;
        max-height: @tabHeight;
        line-height: @tabHeight - 0.1;
        .title {
          font-size: 0.6rem;
        }
      }
  }
}
.no-title-bar:not(.fullscreen).custom-title-bar > atom-workspace atom-panel-container.right {
    margin-top: 0rem;
}
.no-title-bar-right-dock-workaround {
  display: none;
}
```
